Repository salmorejo-hub/uvlhub, pull requests merged in 2024-12, with the labels that each got.

#35 CI/ Sync Salmorejo-hub-2 main to Salmorejo-hub develop
  .github/workflows/ci2.yml
  README.md
  app/templates/base_template.html
Labels: integration

#46 Integration/WI-1.1-1.4-1.6: Remember my password, Rosemary CLI and Discord bot completed
  .env.docker.example
  .env.local.example
  .github/workflows/ci1.yml
  .github/workflows/ci2.yml
  .github/workflows/tests.yml
  app/modules/dataset/seeders.py
  app/modules/dataset/uvl_examples/file1.uvl
  app/modules/dataset/uvl_examples/file10.uvl
  app/modules/dataset/uvl_examples/file11.uvl
  app/modules/dataset/uvl_examples/file12.uvl
  app/modules/dataset/uvl_examples/file2.uvl
  app/modules/dataset/uvl_examples/file3.uvl
  app/modules/dataset/uvl_examples/file4.uvl
  app/modules/dataset/uvl_examples/file5.uvl
  app/modules/dataset/uvl_examples/file6.uvl
  app/modules/dataset/uvl_examples/file7.uvl
  app/modules/dataset/uvl_examples/file8.uvl
  app/modules/dataset/uvl_examples/file9.uvl
  app/modules/explore/routes.py
  app/templates/base_template.html
  discordbot/src/commands/dataset_commands.py
  discordbot/src/util/embeds.py
  discordbot/tests/test_basic_commands.py
  discordbot/tests/test_dataset_commands.py
  discordbot/tests/test_token_commands.py
  docker/docker-compose.dev.yml
  docker/entrypoints/discordbot_entrypoint.sh
  docker/entrypoints/render_entrypoint.sh
  docker/images/Dockerfile.discord
  docker/images/Dockerfile.render
  migrations/versions/c0049aaef0e6_.py
  rosemary/commands/run_app.py
  rosemary/commands/test.py
  rosemary/tests/test_clear_log.py
  rosemary/tests/test_clear_uploads.py
  rosemary/tests/test_compose_env.py
  rosemary/tests/test_coverage.py
  rosemary/tests/test_db_console.py
  rosemary/tests/test_db_table.py
  rosemary/tests/test_db_tables.py
  rosemary/tests/test_env.py
  rosemary/tests/test_module_list.py
Labels: integration

#50 CI/ Sync Salmorejo-hub-2 main to Salmorejo-hub develop
  app/modules/explore/templates/explore/indexSearch.html
  app/modules/exploreuvl/assets/scripts.js
  app/modules/exploreuvl/repositories.py
  app/modules/exploreuvl/routes.py
  app/modules/exploreuvl/services.py
  app/modules/exploreuvl/templates/exploreuvl/index.html
  app/modules/exploreuvl/tests/__init__.py
  app/modules/exploreuvl/tests/locustfile.py
  app/modules/exploreuvl/tests/test_selenium.py
  app/modules/exploreuvl/tests/test_unit.py
  app/modules/featuremodel/models.py
Labels: enhancement, integration

#55 Feat/fakenodo fix: Fakenodo doi generation
  fakenodo/app/routes.py
  fakenodo/app/services.py
Labels: incidence

#61 fix: Remove fakenodo selenium test Closes: #60
  fakenodo/tests/test_selenium.py
Labels: incidence

#64 fix/ flake8 issues Closes #63
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
Labels: incidence

#65 Integration/ WI2.1: Visualize UVL and W2.4: Rate Datasets
  .github/workflows/ci1.yml
  app/modules/api/tests/test_selenium.py
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
  app/modules/explore/templates/explore/indexSearch.html
  app/modules/exploreuvl/assets/scripts.js
  app/modules/exploreuvl/repositories.py
  app/modules/exploreuvl/routes.py
  app/modules/exploreuvl/services.py
  app/modules/exploreuvl/templates/exploreuvl/index.html
  app/modules/exploreuvl/tests/__init__.py
  app/modules/exploreuvl/tests/locustfile.py
  app/modules/exploreuvl/tests/test_selenium.py
  app/modules/exploreuvl/tests/test_unit.py
  app/modules/featuremodel/models.py
  app/modules/featuremodel/tests/test_selenium.py
  app/modules/rating/tests/__init__.py
  app/modules/rating/tests/test_selenium.py
  app/modules/rating/tests/test_unit.py
  app/static/css/app-dark.css
  app/static/css/app.css
  app/static/css/dropzone-dark.css
  app/static/css/own-dark.css
  app/static/css/own.css
  discordbot/src/commands/basic_commands.py
  discordbot/src/commands/dataset_commands.py
  discordbot/src/commands/token_commands.py
  discordbot/src/util/token.py
  docs/Políticas de salmorejo-hub.pdf
  fakenodo/app/routes.py
  fakenodo/app/services.py
  fakenodo/tests/test_selenium.py
  migrations/versions/1b4285af9b16_.py
  requirements.txt
  rosemary/commands/test.py
Labels: integration

#70 CI/ Sync Salmorejo-hub-2 main to Salmorejo-hub develop
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/list_datasets.html
  app/modules/exploreuvl/assets/scripts.js
  app/modules/exploreuvl/repositories.py
  app/modules/exploreuvl/services.py
  app/modules/exploreuvl/templates/exploreuvl/index.html
  app/modules/exploreuvl/tests/test_unit.py
  app/modules/featuremodel/models.py
  app/modules/zenodo/services.py
  fakenodo/app/services.py
Labels: enhancement, integration

#75 Integration/WI2.6: Search Queries
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/list_datasets.html
  app/modules/exploreuvl/assets/scripts.js
  app/modules/exploreuvl/repositories.py
  app/modules/exploreuvl/services.py
  app/modules/exploreuvl/templates/exploreuvl/index.html
  app/modules/exploreuvl/tests/test_unit.py
  app/modules/featuremodel/models.py
  app/modules/zenodo/services.py
  discordbot/src/commands/dataset_commands.py
  fakenodo/app/services.py
Labels: integration

#92 fix/Selenium test update dataset [Closes #91]
  app/modules/dataset/tests/test_selenium.py
Labels: incidence

#90 CI/ Sync Salmorejo-hub-2 main to Salmorejo-hub develop
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/list_datasets.html
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
Labels: integration

#94 Integration/ WI2.3: Improve UI and WI2.5 Stagging area
  .github/workflows/render.yml
  app/modules/auth/seeders.py
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/list_datasets.html
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
  app/modules/pytest.ini
  app/static/__init__.py
  app/static/css/app-dark(progreso).css
  app/static/css/app-dark.css
  app/static/js/app.js
  app/static/js/tests/__init__.py
  app/static/js/tests/test_selenium.py
  app/static/js/tests/test_unit.py
  app/static/js/theme-toggle.js
  app/templates/400.html
  app/templates/401.html
  app/templates/404.html
  app/templates/500.html
  app/templates/base_template.html
  discordbot/pytest.ini
  discordbot/src/commands/dataset_commands.py
  discordbot/src/commands/token_commands.py
  discordbot/tests/test_dataset_commands.py
Labels: enhancement, integration
